language: node_js
sudo: false
matrix:
  include:
    - node_js: "6"
  fast_finish: true
git:
  depth: 5
env:
  - "NODE_FLAGS='--expose-gc' SCRIPT_FLAGS=''"
before_script:
- git submodule update --init --recursive
script: "node $NODE_FLAGS tools/test.js $SCRIPT_FLAGS"
branches:
  only:
    - master
